### PR TITLE
Create ParseAddress.py

### PR DESCRIPTION
**Pull request by vanigupta20024**

### CODE REVIEW

**Review by saikat1506 — APPROVED** [review]

**Review by saikat1506 — APPROVED** [review]

**Review by saikat1506 — APPROVED** [review]

**Review by saikat1506 — APPROVED** [review]

**Review by saikat1506 — CHANGES_REQUESTED** [review]
Provide the Input labels to be entered by user, EG:-"Enter the Tax Percentage"

**Review by saikat1506 — CHANGES_REQUESTED** [review]
Provide the Input labels to be entered by an user, EG:-"Enter a Number here", 
Refer PEP 8 -- Style Guide for Python Code...

**Comment by vanigupta20024** [comment]
Updated both the files as mentioned by you.

**Comment by vanigupta20024** [comment]
Added code for Hackerrank Day 6&7

**Pull request merged**
