### PR TITLE
Added Day 14 to Day 20 Codes + Homophonic Cipher + Vigenere Cipher + Cipher GUI

### PR DESCRIPTION
**Pull request by SaloniSwagata**

### CODE REVIEW

**Review by Yukti-09 — COMMENTED** [review]
print(f"Encrypted message: {enc}")                                                                                  
                                    ^                                                                                   
SyntaxError: invalid syntax   
This issue seems to be there for all the codes, verify and let me know.

**Review by Yukti-09 — COMMENTED** [review]
It's homophonic and not homophobic

**Comment by SaloniSwagata** [comment]
> ```
> print(f"Encrypted message: {enc}")                                                                                  
>                                 ^                                                                                   
> ```
> 
> SyntaxError: invalid syntax
> This issue seems to be there for all the codes, verify and let me know.

No, it's not an error, my codes are working fine. This is a shortcut method to print formatted texts in python 3

**Comment by SaloniSwagata** [comment]
> It's homophonic and not homophobic

Yes, I will change the names. Thanks!

**Comment by Yukti-09** [comment]
> > ```
> > print(f"Encrypted message: {enc}")                                                                                  
> >                                 ^                                                                                   
> > ```
> > 
> > 
> > SyntaxError: invalid syntax
> > This issue seems to be there for all the codes, verify and let me know.
> 
> No, it's not an error, my codes are working fine. This is a shortcut method to print formatted texts in python 3

Try doing it without the formatting, I need to run it to validate it.

**Comment by SaloniSwagata** [comment]
> > > ```
> > > print(f"Encrypted message: {enc}")                                                                                  
> > >                                 ^                                                                                   
> > > ```
> > > 
> > > 
> > > SyntaxError: invalid syntax
> > > This issue seems to be there for all the codes, verify and let me know.
> > 
> > 
> > No, it's not an error, my codes are working fine. This is a shortcut method to print formatted texts in python 3
> 
> Try doing it without the formatting, I need to run it to validate it.

Okay! I'll do it and inform you.

**Pull request merged**
